info:
  component: Edge Server

spring:
  application:
    name: service-zuul-ui

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    foos:
      path: /foos/**
      serviceId: foo-service

#url: http://10.242.136.100:8081/foos
#serviceId: foo-service


## without eureka
## foo-service:
##  ribbon:
##    listOfServers: http://10.242.136.100:8081,http://10.242.136.100:8082

## Disabled Eureka service discovery component, by setting eureka: enabled to false
#foo-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: 10.242.136.100:8081,10.242.136.100:8082
#    ServerListRefreshInterval: 1000

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

routing:
  tag:
    domain: qa-blue.igame.163.com

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG